apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hc.fullname" . }}
  labels:
    {{- include "hc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hc.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            initialDelaySeconds: 20
          volumeMounts:
            - name: config-vl
              mountPath: /config
            - name: data
              mountPath: /data
          env:
            - name: CONFIG
              value: "/config/config.json"
            {{- range $k,$v :=.Values.configEnv }}
            - name: {{ $k }}
              value: {{quote $v }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-vl
          configMap:
            name: {{ .Chart.Name }}-config-configmap
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc-data

