# Default values for hc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost/hc
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

pvPath: "/var/tmp/pv"

nfs:
  enabled: false
  path: "/home/pv"
  server: "172.16.10.123"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

configEnv:
  DEBUG: "1"
  MSG: "helm chart msg"

config:
  name: "Cheng"
  date: "2023/03/05 15:05:05"
  age: 28
  counter: 4
